import { useEffect, useRef, useState } from 'react';
import { Archive, Download, MessageSquare, Paperclip, Pencil, Trash2, Undo2, X } from 'lucide-react';
import { Fields } from './App';
import { deleteTicket, loadAttachments, loadComments, removeFile, updateTicket, uploadFile } from './api';
import { bucket, errorMessage, fileSize, supabase } from './lib';
import type { Attachment, Comment, Draft, Ticket } from './types';
export function TicketDetail({ ticket, close, changed, deleted, notify }: { ticket: Ticket; close(): void; changed(ticket: Ticket): void; deleted(id: number): void; notify(message: string): void }) {
  const [draft, setDraft] = useState<Draft>({ title: ticket.title, description: ticket.description, due_date: ticket.due_date, priority: ticket.priority, status: ticket.status });
  const [comments, setComments] = useState<Comment[]>([]);
  const [files, setFiles] = useState<Attachment[]>([]);
  const [comment, setComment] = useState('');
  const [editingComment, setEditingComment] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  const lock = useRef(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const dirty = draft.title !== ticket.title || draft.description !== ticket.description || draft.due_date !== ticket.due_date || draft.priority !== ticket.priority || draft.status !== ticket.status;
  const tryClose = () => { if (!busy && (!(dirty || comment.trim()) || window.confirm('Discard unsaved changes?'))) close(); };
  useEffect(() => {
    dialog.current?.showModal();
    let alive = true;
    Promise.all([loadComments(ticket.id), loadAttachments(ticket.id)]).then(([c, f]) => { if (alive) { setComments(c); setFiles(f); } }).catch(e => { if (alive) setError(errorMessage(e)); }).finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [ticket.id]);
  async function run(task: () => Promise<void>) {
    if (lock.current) return;
    lock.current = true; setBusy(true); setError('');
    try { await task(); } catch (e) { setError(errorMessage(e)); } finally { lock.current = false; setBusy(false); }
  }
  return <dialog ref={dialog} className="detail-dialog" onCancel={e => { e.preventDefault(); tryClose(); }}><div className="detail-heading"><div><span className="number">#{ticket.id}</span><span className="detail-label">{ticket.archived ? 'Archived ticket' : 'Ticket details'}</span></div><button className="icon-button" aria-label="Close ticket" disabled={busy} onClick={tryClose}><X size={20}/></button></div><div className="detail-body">
    {error && <p className="error-banner" role="alert">{error}</p>}<form onSubmit={e => { e.preventDefault(); void run(async () => { changed(await updateTicket(ticket.id, { ...draft, title: draft.title.trim() })); notify(`Ticket #${ticket.id} updated`); }); }}><fieldset disabled={busy}><label>Ticket title<input autoFocus required maxLength={500} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })}/></label><Fields draft={draft} change={setDraft}/><label>Description<textarea rows={4} value={draft.description} placeholder="Optional" onChange={e => setDraft({ ...draft, description: e.target.value })}/></label></fieldset><div className="detail-save"><span className="muted">Created {new Date(ticket.created_at).toLocaleDateString()}</span><button className="primary" disabled={busy || !draft.title.trim() || !dirty}>Save changes</button></div></form>
    <section className="detail-section"><div className="section-label"><MessageSquare size={17}/><h2>Comments</h2><span>{comments.length}</span></div>{loading && <p className="muted">Loading…</p>}<div className="comments">{comments.map(c => <article className="comment" key={c.id}><p>{c.body}</p><div><time>{new Date(c.created_at).toLocaleString()}{c.updated_at !== c.created_at ? ' · edited' : ''}</time><button className="icon-button" aria-label="Edit comment" disabled={busy} onClick={() => { setComment(c.body); setEditingComment(c.id); }}><Pencil size={14}/></button><button className="icon-button danger" aria-label="Delete comment" disabled={busy} onClick={() => { if (window.confirm('Delete this comment?')) void run(async () => { const { error } = await supabase.from('personal_ticket_comments').delete().eq('id', c.id); if (error) throw error; setComments(items => items.filter(item => item.id !== c.id)); if (editingComment === c.id) { setEditingComment(null); setComment(''); } }); }}><Trash2 size={14}/></button></div></article>)}</div><form onSubmit={e => { e.preventDefault(); void run(async () => { const result = editingComment ? await supabase.from('personal_ticket_comments').update({ body: comment.trim() }).eq('id', editingComment).select().single() : await supabase.from('personal_ticket_comments').insert({ ticket_id: ticket.id, body: comment.trim() }).select().single(); if (result.error) throw result.error; setComments(items => editingComment ? items.map(c => c.id === editingComment ? result.data : c) : [...items, result.data]); setComment(''); setEditingComment(null); }); }}><textarea aria-label="Comment" placeholder="Add a comment…" rows={2} maxLength={20000} value={comment} onChange={e => setComment(e.target.value)} disabled={busy}/><div className="comment-actions">{editingComment && <button type="button" className="text-button" onClick={() => { setComment(''); setEditingComment(null); }}>Cancel edit</button>}<button className="secondary" disabled={busy || !comment.trim()}>{editingComment ? 'Save comment' : 'Add comment'}</button></div></form></section>
    <section className="detail-section"><div className="section-label"><Paperclip size={17}/><h2>Files</h2><span>{files.length}</span></div><div className="files">{files.map(file => <div className="file" key={file.id}><Paperclip size={17}/><div><strong>{file.name}</strong><small>{fileSize(file.size)}</small></div><button className="icon-button" aria-label={`Download ${file.name}`} disabled={busy} onClick={() => void run(async () => { const { data, error } = await supabase.storage.from(bucket).download(file.path); if (error) throw error; const url = URL.createObjectURL(data); const link = document.createElement('a'); link.href = url; link.download = file.name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 60000); })}><Download size={17}/></button><button className="icon-button danger" aria-label={`Delete ${file.name}`} disabled={busy} onClick={() => { if (window.confirm(`Delete ${file.name}?`)) void run(async () => { await removeFile(file); setFiles(items => items.filter(f => f.id !== file.id)); }); }}><Trash2 size={17}/></button></div>)}</div><input ref={fileInput} type="file" multiple className="sr-only" aria-label="Upload files" disabled={busy || loading} onChange={e => { const selected = Array.from(e.target.files || []); e.target.value = ''; void run(async () => { for (const file of selected) { await uploadFile(ticket, file); setFiles(await loadAttachments(ticket.id)); } notify('Files uploaded'); }); }}/><button className="upload-button" disabled={busy || loading} onClick={() => fileInput.current?.click()}><Paperclip size={17}/>{busy ? 'Working…' : 'Upload files'}<span>Up to 25 MB each</span></button></section>
  </div><footer className="detail-footer">{confirmDelete ? <div className="delete-confirm"><p>Delete this ticket, comments, and files permanently?</p><button className="secondary" disabled={busy} onClick={() => setConfirmDelete(false)}>Cancel</button><button className="danger-button" disabled={busy} onClick={() => void run(async () => { await deleteTicket(ticket); deleted(ticket.id); })}>Delete permanently</button></div> : <><button className="secondary" disabled={busy} onClick={() => void run(async () => { const updated = await updateTicket(ticket.id, { archived: !ticket.archived }); changed(updated); notify(updated.archived ? 'Ticket archived' : 'Ticket restored'); })}>{ticket.archived ? <Undo2 size={17}/> : <Archive size={17}/>} {ticket.archived ? 'Restore' : 'Archive'}</button><button className="text-button danger" disabled={busy} onClick={() => setConfirmDelete(true)}><Trash2 size={17}/>Delete ticket</button></>}</footer></dialog>;
}
